"""
Golf Quant Engine — Quant System Tab
======================================
Dashboard from report_service.
CLV tracking from bet_service.get_clv_summary().
System state from report_service.get_system_state().
"""

import streamlit as st

from streamlit_app.config import SYSTEM_STATE_COLORS
from streamlit_app.components.charts import (
    render_calibration_chart,
    render_clv_chart,
    render_pnl_curve,
)

from services.report_service import (
    get_latest_report,
    get_report_history,
    get_calibration_data,
    get_system_state,
    get_sg_accuracy_report,
)
from services.bet_service import (
    get_clv_summary,
    get_pnl_summary,
    get_settled_bets,
)


def render() -> None:
    """Render the Quant System tab. All data from DB."""
    st.markdown("# \U0001f9ee Quant System")

    # System state banner
    _render_system_state()

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        _render_clv_tracking()
        _render_calibration()

    with col2:
        _render_performance_dashboard()
        _render_daily_report()


def _render_system_state() -> None:
    """Display current system state with kill-switch status."""
    sys_state = get_system_state()
    state = sys_state.get("state", "UNKNOWN")
    icon = SYSTEM_STATE_COLORS.get(state, "\u26aa")
    reason = sys_state.get("reason", "")
    changed_at = sys_state.get("changed_at", "")

    # State banner
    if state == "ACTIVE":
        st.success(f"{icon} System State: **{state}**")
    elif state == "REDUCED":
        st.warning(f"{icon} System State: **{state}** -- {reason}")
    elif state in ("SUSPENDED", "KILLED"):
        st.error(f"{icon} System State: **{state}** -- {reason}")
    else:
        st.info(f"{icon} System State: **{state}**")

    if changed_at:
        st.caption(f"State changed at: {changed_at}")

    # Key metrics at time of state change
    metrics_cols = st.columns(3)

    clv = sys_state.get("clv_at_change")
    bankroll = sys_state.get("bankroll_at_change")
    drawdown = sys_state.get("drawdown_at_change")

    if clv is not None:
        metrics_cols[0].metric("CLV at Change", f"{clv:+.4f}")
    if bankroll is not None:
        metrics_cols[1].metric("Bankroll at Change", f"${bankroll:,.2f}")
    if drawdown is not None:
        metrics_cols[2].metric("Drawdown at Change", f"{drawdown*100:.1f}%")

    # State history
    history = sys_state.get("history", [])
    if history and len(history) > 1:
        with st.expander("State Change History"):
            for h in history:
                h_state = h.get("state", "")
                h_reason = h.get("reason", "")
                h_time = h.get("changed_at", "")
                h_icon = SYSTEM_STATE_COLORS.get(h_state, "\u26aa")
                st.caption(f"{h_icon} {h_state}: {h_reason} ({h_time})")


def _render_clv_tracking() -> None:
    """Display CLV summary and per-market breakdown."""
    st.markdown("### CLV Tracking")

    clv_data = get_clv_summary(window=100)
    render_clv_chart(clv_data)


def _render_calibration() -> None:
    """Display model calibration chart from calibration snapshots."""
    st.markdown("### Model Calibration")

    calibration = get_calibration_data()

    if not calibration:
        st.info(
            "No calibration data available yet. "
            "Calibration snapshots are generated by the report_worker "
            "once enough bets have been settled."
        )
        return

    render_calibration_chart(calibration)

    # Calibration error summary
    total_bets = sum(d.get("n_bets", 0) for d in calibration)
    avg_error = 0
    if calibration:
        errors = [d.get("calibration_error", 0) for d in calibration]
        avg_error = sum(errors) / len(errors)

    col1, col2 = st.columns(2)
    col1.metric("Total Calibrated Bets", total_bets)
    col2.metric("Avg Calibration Error", f"{avg_error:.4f}")


def _render_performance_dashboard() -> None:
    """Display key performance metrics from bet_service and report_service."""
    st.markdown("### Performance Dashboard")

    # All-time P&L
    pnl_all = get_pnl_summary("all")
    pnl_monthly = get_pnl_summary("monthly")
    pnl_weekly = get_pnl_summary("weekly")

    col1, col2, col3 = st.columns(3)

    total_pnl = pnl_all.get("total_pnl", 0)
    col1.metric(
        "All-Time P&L",
        f"${total_pnl:+.2f}",
        delta=f"ROI: {pnl_all.get('roi', 0)*100:+.1f}%",
        delta_color="normal" if total_pnl >= 0 else "inverse",
    )

    monthly_pnl = pnl_monthly.get("total_pnl", 0)
    col2.metric(
        "Monthly P&L",
        f"${monthly_pnl:+.2f}",
        delta=f"{pnl_monthly.get('bets_settled', 0)} bets",
    )

    weekly_pnl = pnl_weekly.get("total_pnl", 0)
    col3.metric(
        "Weekly P&L",
        f"${weekly_pnl:+.2f}",
        delta=f"Win: {pnl_weekly.get('win_rate', 0)*100:.0f}%",
    )

    # SG accuracy
    accuracy = get_sg_accuracy_report()
    if accuracy.get("sample_size", 0) > 0:
        st.markdown("**Model Accuracy:**")
        acc_cols = st.columns(3)
        acc_cols[0].caption(
            f"Directional: {accuracy.get('overall_accuracy', 0)*100:.1f}%"
        )
        acc_cols[1].caption(
            f"Avg Error: {accuracy.get('avg_absolute_error', 0):.3f}"
        )
        acc_cols[2].caption(f"n = {accuracy.get('sample_size', 0)}")

    # P&L curve
    settled = get_settled_bets(days=90)
    if settled:
        settled_chrono = list(reversed(settled))
        render_pnl_curve(settled_chrono)


def _render_daily_report() -> None:
    """Display latest daily edge report."""
    st.markdown("### Latest Report")

    report = get_latest_report("daily")

    if not report:
        st.info("No daily reports generated yet. Reports are created by the report_worker.")
        return

    st.caption(f"Generated: {report.get('generated_at', 'unknown')}")

    data = report.get("data", {})
    if not data:
        st.caption("Report has no data payload.")
        return

    # Display report data
    if isinstance(data, dict):
        # Show key metrics from the report
        for key, value in data.items():
            if isinstance(value, (int, float)):
                st.caption(f"**{key}**: {value}")
            elif isinstance(value, str):
                st.caption(f"**{key}**: {value}")
            elif isinstance(value, dict):
                with st.expander(f"Detail: {key}"):
                    st.json(value)
            elif isinstance(value, list) and len(value) > 0:
                with st.expander(f"Detail: {key} ({len(value)} items)"):
                    for item in value[:10]:
                        st.json(item) if isinstance(item, dict) else st.write(item)

    # Report history
    history = get_report_history("daily", days=7)
    if len(history) > 1:
        with st.expander(f"Report History ({len(history)} reports, last 7 days)"):
            for r in history:
                st.caption(
                    f"{r.get('generated_at', '')} -- "
                    f"Type: {r.get('report_type', '')}"
                )
